global proc refQueryCSharpTest()
{
	file -force -new;
	loadPlugin -qt examples.nll.dll;

	// create file
	file -rename "testRefQuery.ma";
	file -save;

	// create Reference
	file -new -force;
	file -r "testRefQuery.ma";

	// ref query
	refQueryCSharp;
	// output:
	//  //Referenced File: testRefQuery.ma:
	//		Connections Made:
	//		Connections Broken: 
	//		Attrs Changed Since File Open:
	//		=====================================// 
} 

refQueryCSharpTest();
